options(max.print = 3000)
library(foreign)
#read.dta("there/is/your/file/directory/filename.dta",convert.factors=F)
a1 <- read.dta("C:/Users/huangyg/Desktop/charls/2013 CHARLS Wave2/Demographic_Background.dta",convert.factors=F)
a2 <- read.dta("C:/Users/huangyg/Desktop/charls/2013 CHARLS Wave2/Family_Information.dta",convert.factors=F)
a3 <- read.dta("C:/Users/huangyg/Desktop/charls/2013 CHARLS Wave2/Family_Transfer.dta",convert.factors=F)
a4 <- read.dta("C:/Users/huangyg/Desktop/charls/2013 CHARLS Wave2/Health_Care_and_Insurance.dta",convert.factors=F)
a5 <- read.dta("C:/Users/huangyg/Desktop/charls/2013 CHARLS Wave2/Health_Status_and_Functioning.dta",convert.factors=F)
a6 <- read.dta("C:/Users/huangyg/Desktop/charls/2013 CHARLS Wave2/Household_Income.dta",convert.factors=F)
a7 <- read.dta("C:/Users/huangyg/Desktop/charls/2013 CHARLS Wave2/Housing_Characteristics.dta",convert.factors=F)
a8 <- read.dta("C:/Users/huangyg/Desktop/charls/2013 CHARLS Wave2/Individual_Income.dta",convert.factors=F)
a9 <- read.dta("C:/Users/huangyg/Desktop/charls/2013 CHARLS Wave2/Interviewer_Observation.dta",convert.factors=F)
a10 <- read.dta("C:/Users/huangyg/Desktop/charls/2013 CHARLS Wave2/PSU.dta",convert.factors=F)
a11 <- read.dta("C:/Users/huangyg/Desktop/charls/2013 CHARLS Wave2/Weights.dta",convert.factors=F)
a12 <- read.dta("C:/Users/huangyg/Desktop/charls/2013 CHARLS Wave2/Work_Retirement_and_Pension.dta",convert.factors=F)

sum(is.na(a1))
mean(is.na(a1))
sum(is.na(a2))
mean(is.na(a2))
sum(is.na(a3))
mean(is.na(a3))
sum(is.na(a4))
mean(is.na(a4))
sum(is.na(a5))
mean(is.na(a5))
sum(is.na(a6))
mean(is.na(a6))
sum(is.na(a7))
mean(is.na(a7))
sum(is.na(a8))
mean(is.na(a8))
sum(is.na(a9))
mean(is.na(a9))
sum(is.na(a10))
mean(is.na(a10))
sum(is.na(a11))
mean(is.na(a11))
sum(is.na(a12))
mean(is.na(a12))
