options(max.print = 3000)
library(foreign)
#read.dta("there/is/your/file/directory/filename.dta",convert.factors=F)
a <- read.dta("C:/Users/huangyg/Desktop/charls/Demographic_Background.dta",convert.factors=F)
attach(a)
plot(ba002_1,zba002_1)